version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8001
      - PRODUCT_SERVICE_URL=http://product_service:8002
      - CART_SERVICE_URL=http://cart_service:8003
      - ORDER_SERVICE_URL=http://order_service:8004
      - REVIEW_SERVICE_URL=http://review_service:8007
    depends_on:
      - auth_service
      - product_service
      - cart_service
      - order_service
      - review_service

  auth_service:
    build: ./auth_service

  product_service:
    build: ./product_service

  cart_service:
    build: ./cart_service

  order_service:
    build: ./order_service
    environment:
      - PAYMENT_SERVICE_URL=http://payment_service:8005
      - NOTIFICATION_SERVICE_URL=http://notification_service:8006
    depends_on:
      - payment_service
      - notification_service

  payment_service:
    build: ./payment_service

  notification_service:
    build: ./notification_service
    
  review_service:
    build: ./review_service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway
